version: "2.0"
services:
    nginx:
        image: tutum/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
            - db
        volumes:
            - ./nginx/default:/etc/nginx/sites-available/default
            - ./nginx/default:/etc/nginx/sites-enabled/default

            - ./logs/nginx-error.log:/var/log/nginx/error.log
            - ./logs/nginx-access.log:/var/log/nginx/access.log

    phpfpm:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            -  ./app:/var/www/html/

    db:
      image: mariadb
      restart: always
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: locally
        MYSQL_PASSWORD: qwerty
        MYSQL_DATABASE: database
      ports:
        - "8889:3306"

    mailhog:
      image: mailhog/mailhog:latest
      container_name: locally-mailhog
      ports:
        - "1801:8025"

    redis:
      image: redis:alpine
      container_name: locally-redis


    mariadb:
      image: mariadb:10.1
      container_name: locally-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=ro
        - MYSQL_DATABASE=database
        - MYSQL_USER=locally
        - MYSQL_PASSWORD=root
      ports:
        - "1803:3306"
