version: "3.0"
services:

    nginx:
        image: nginx
        restart: always
        ports:
            - 8080:80
        environment:
            - NGINX_HOST= localhost
            - NGINX_PORT= 80
        links:
            - phpfpm
            - db
        volumes:
            - ./nginx/default:/etc/nginx/sites-available/default
            - ./nginx/default:/etc/nginx/sites-enabled/default

            - ./logs/nginx-error.log:/var/log/nginx/error.log
            - ./logs/nginx-access.log:/var/log/nginx/access.log

    phpfpm:
        image: php:fpm
        ports:
            - 9000:9000
        volumes:
            -  ./app:/var/www/html/

    db:
      image: mariadb
      restart: always
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: locally
        MYSQL_PASSWORD: qwerty
        MYSQL_DATABASE: database
      ports:
        - 8889:3306

    mailhog:
      image: mailhog/mailhog:latest
      container_name: locally-mailhog
      restart: always
      ports:
        - 1801:8025

    redis:
      image: redis:alpine
      container_name: locally-redis
      restart: always
      ports:
        - 6379:6379


    redis-commander:
      container_name: ${PROJECT_NAME}_redis_commander
      hostname: locally-redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      links:
          - redis
      environment:
          - REDIS_HOST=redis
          - REDIS_PORT=6379
      ports:
          - 6081:8081